### PR TITLE
feat: implement PlutusSemantic versioning support with security fixes

### LINKED ISSUE #82: handle PlutusSemantic Versioning
There is a thing known as BuiltinSemantics and there is a V1 and V2. This mostly only affects consByteString.

### PR DESCRIPTION
**Pull request by wolf31o2**
- Add Plutus V1/V2/V3 version support with automatic cost model selection
- Implement version-aware builtin functions (consByteString constraints)
- Add comprehensive security fixes for integer overflow vulnerabilities
- Update README example to demonstrate Plutus V3 usage
- Pass all tests and linting checks

Closes #82 

---
## Summary by cubic
Adds Plutus semantic versioning (V1/V2/V3) with automatic cost model selection and hardens integer handling to prevent overflows. Evaluation is now version-aware, safer, and the README example shows Plutus V3.

- **New Features**
  - Plutus V1/V2/V3 support with version-driven cost model selection.
  - Machine constructor now accepts program version; added helper to create with version-appropriate costs.
  - README updated; examples use 1.2.0 (Plutus V3).

- **Bug Fixes**
  - Added bounds checks for constructor tags, DeBruijn indices, and flat encode/decode bit math; reject negative and oversized values.
  - Hardened builtins and parser (e.g., consByteString enforces 0–255; non-negative constr tags) to avoid integer overflow/underflow.
  - Enabled gosec in linting and tightened output file permissions to 0600.

<sup>Written for commit 56010e82fab2c0f6712e02cbcc421b782a83b77b. Summary will update automatically on new commits.</sup>

## Summary by CodeRabbit

* **New Features**
  * Added support for Plutus V1, V2, and V3 with automatic cost model selection based on program version
  * Version-aware machine initialization

* **Bug Fixes**
  * Improved validation for constructor tags, byte strings, and DeBruijn indices
  * Enhanced bounds checking for version numbers and integer conversions

* **Documentation**
  * Expanded README with Features section and Plutus Version Support details
  * Added version-aware initialization examples

* **Tests**
  * Added tests for machine version initialization and cost model handling

* **Chores**
  * Enhanced linting configuration with improved security checks

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: syn/flat_decode.go [hunk 1]
```diff
@@ -523,18 +528,15 @@ func (d *decoder) bits8(numBits byte) (byte, error) {
...
-	d.usedBits = int64(allUsedBits) % 8
+	d.usedBits = allUsedBits % 8
 
-	d.pos += int(allUsedBits) / 8
+	d.pos += int(allUsedBits / 8)
 }
 
-// Ensures the buffer has the required bits passed in by required_bits.
-// Throws a NotEnoughBits error if there are less bits remaining in the
-// buffer than required_bits.
```
Comment (agaffney) [inline syn/flat_decode.go]: We should keep this comment

File: syn/flat_encode.go [hunk 2]
```diff
@@ -184,7 +184,7 @@ func (e *encoder) encodeTermTag(tag byte) error {
 }
 
 func (e *encoder) safeEncodeBits(numBits byte, val byte) error {
-	if 2<<numBits <= val {
+	if val >= (1 << numBits) {
```
Comment (agaffney) [inline syn/flat_encode.go]: Is this actually correct? Does changing the order/operator of the comparison here require changing the number of bits that were shifting?

**Review by agaffney — APPROVED** [review]

**Comment by wolf31o2** [comment]
@coderabbitai review

File: syn/flat_encode.go (hunk 2 above)
Comment (wolf31o2) [reply syn/flat_encode.go]: So... there's a lot of math explanation here, but the answer is

> Answer to Your Question
> No, the number of bits doesn't need to change. The original condition was using the wrong mathematical threshold. The bit count numBits is correct - the issue was that `2<<numBits` was checking against `2^(numBits+1)` instead of `2^numBits`.
>
> This was a critical bug fix that prevented silent truncation of values that don't > fit in the allocated bit space, which could lead to incorrect Plutus term encoding.
